services:

  taskmanager-app:

    image: taskmanager:1.0

    container_name: taskmanager-app

    ports:
      - "8083:8083"

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: 86400000